### ISSUE TITLE
PE 2015.2: The expression <init xl-release> is not a valid type specification

### ISSUE THREAD

**Issue by ltutar** [xebialabs/puppet-xlrelease#10]
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a '->' expression, The expression <init xl-release> is not a valid type specification. at /etc/puppetlabs/code/environments/production/modules/xlrelease/manifests/config.pp:40:3 on node puppetagent1.home
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

The code was:
  -> Exec ['init xl-release']
and works when the space between Exec and [ is removed.
Now:
  -> Exec['init xl-release']

**Comment by WianVos** [comment]
so where's the pull request

**Comment by ltutar** [comment]
You may not have permission to access puppet-xlrelease. Check Preferences to make sure you’re still logged in.

On 22 Oct 2015, at 18:17, WianVos <notifications@github.com<mailto:notifications@github.com>> wrote:

so where's the pull request
