### ISSUE TITLE
PE2015.2: Use of reserved word: type, must be quoted if intended to be a String value

### ISSUE THREAD

**Issue by ltutar** [xebialabs/puppet-xlrelease#11]
I get the error:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Use of reserved word: type, must be quoted if intended to be a String value at /etc/puppetlabs/code/environments/production/modules/xlrelease/manifests/postconfig.pp:16:5 on node puppetagent1.home

Solution:

remove the line
  type     => 'xlrelease.DeployitServerDefinition',
from the file xlrelease/manifests/postconfig.pp

**Comment by ltutar** [comment]
Changing it to type_of does not solve the problem.
When I want to register xldeploy in xlrelease, I get the error:
[root@puppetagent1 ~]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter: 'type_of' on Xlrelease_xld_server[xldeploy] on node puppetagent1.home
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by ltutar** [comment]
The same for jenkins also.

Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter: 'type_of' on Xlrelease_config_item[jenkins] on node puppetagent1.home
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by ltutar** [comment]
couldn't get jenkins working

**Comment by WianVos** [comment]
so where is the pull request ?

**Comment by WianVos** [comment]
done
