### ISSUE TITLE
Error: Facter: error while resolving custom facts in /opt/puppetlabs/puppet/cache/lib/facter/xlrelease_facts.rb: undefined method `chomp' for nil:NilClass

### ISSUE THREAD

**Issue by ltutar** [xebialabs/puppet-xlrelease#15]
I had the option xlr_ssl set to true. The puppet run failed. Then I set to false which is the default value. 
The puppet run gives the following error:

[root@puppetagent1 ~]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Facter: error while resolving custom facts in /opt/puppetlabs/puppet/cache/lib/facter/xlrelease_facts.rb: undefined method `chomp' for nil:NilClass
Info: Caching catalog for puppetagent1.home
Info: Applying configuration version '1444973049'
Notice: /Stage[main]/Xlrelease::Config/Exec[init xl-release]/returns: 2015-10-16 07:24:13.955 [main] {} INFO  c.x.xlrelease.XLReleaseBootstrapper - XL Release version 4.7.2 (built at 15-10-06 10:32:34)
Notice: /Stage[main]/Xlrelease::Config/Exec[init xl-release]/returns: 2015-10-16 07:24:13.959 [main] {} INFO  c.x.xlrelease.XLReleaseBootstrapper - (c) 2012-2015 XebiaLabs
Notice: /Stage[main]/Xlrelease::Config/Exec[init xl-release]/returns: 
Notice: /Stage[main]/Xlrelease::Config/Exec[init xl-release]/returns: 2015-10-16 07:24:14.098 [main] {} INFO  c.x.xlrelease.XLReleaseBootstrapper - Reading configuration file from: /opt/xl-release/xl-release-4.7.2-server/conf/xl-release-server.conf
Notice: /Stage[main]/Xlrelease::Config/Exec[init xl-release]/returns: 2015-10-16 07:24:14.116 [main] {} INFO  c.x.deployit.ServerConfiguration - Read plaintext admin password from the file, marking as dirty to save encrypted.
Notice: /Stage[main]/Xlrelease::Config/Exec[init xl-release]/returns: 2015-10-16 07:24:14.119 [main] {} ERROR c.x.xlrelease.XLReleaseBootstrapper - Could not start XL Release
Notice: /Stage[main]/Xlrelease::Config/Exec[init xl-release]/returns: java.lang.NullPointerException: null
Notice: /Stage[main]/Xlrelease::Config/Exec[init xl-release]/returns:   at java.util.Hashtable.put(Hashtable.java:514) ~[na:1.7.0_85]
Notice: /Stage[main]/Xlrelease::Config/Exec[init xl-release]/returns:   at java.util.Properties.setProperty(Properties.java:161) ~[na:1.7.0_85]
Notice: /Stage[main]/Xlrelease::Config/Exec[init xl-release]/returns:   at com.xebialabs.deployit.ServerConfiguration.save(ServerConfiguration.java:289) ~[appserver-core-2015.5.2.jar:na]
Notice: /Stage[main]/Xlrelease::Config/Exec[init xl-release]/returns:   at com.xebialabs.deployit.ServerConfigFile.writeConfiguration(ServerConfigFile.java:80) ~[appserver-core-2015.5.2.jar:na]
Notice: /Stage[main]/Xlrelease::Config/Exec[init xl-release]/returns:   at com.xebialabs.deployit.setup.Setup.reinitialize(Setup.java:138) ~[appserver-main-2015.5.2.jar:na]
Notice: /Stage[main]/Xlrelease::Config/Exec[init xl-release]/returns:   at com.xebialabs.deployit.setup.Setup.run(Setup.java:110) ~[appserver-main-2015.5.2.jar:na]
Notice: /Stage[main]/Xlrelease::Config/Exec[init xl-release]/returns:   at com.xebialabs.xlrelease.XLReleaseBootstrapper.startSetup(XLReleaseBootstrapper.java:97) ~[server-4.7.2.jar:na]
Notice: /Stage[main]/Xlrelease::Config/Exec[init xl-release]/returns:   at com.xebialabs.xlrelease.XLReleaseBootstrapper.start(XLReleaseBootstrapper.java:64) ~[server-4.7.2.jar:na]
Notice: /Stage[main]/Xlrelease::Config/Exec[init xl-release]/returns:   at com.xebialabs.xlrelease.XLReleaseBootstrapper.main(XLReleaseBootstrapper.java:49) ~[server-4.7.2.jar:na]
Notice: /Stage[main]/Xlrelease::Config/Exec[init xl-release]/returns: null
Error: /opt/xl-release/xl-release-server/bin/server.sh -setup -reinitialize -force -setup-defaults /opt/xl-release/xl-release-server/conf/xl-release-server.conf returned 1 instead of one of [0]
Error: /Stage[main]/Xlrelease::Config/Exec[init xl-release]/returns: change from notrun to 0 failed: /opt/xl-release/xl-release-server/bin/server.sh -setup -reinitialize -force -setup-defaults /opt/xl-release/xl-release-server/conf/xl-release-server.conf returned 1 instead of one of [0]
Notice: /Stage[main]/Xlrelease::Config/Anchor[xlr config_end]: Dependency Exec[init xl-release] has failures: true
Warning: /Stage[main]/Xlrelease::Config/Anchor[xlr config_end]: Skipping because of failed dependencies
Notice: /Stage[main]/Xlrelease::Service/Service[xl-release]: Dependency Exec[init xl-release] has failures: true
Warning: /Stage[main]/Xlrelease::Service/Service[xl-release]: Skipping because of failed dependencies
Notice: /Stage[main]/Xlrelease::Service/Xlrelease_check_connection[default]: Dependency Exec[init xl-release] has failures: true
Warning: /Stage[main]/Xlrelease::Service/Xlrelease_check_connection[default]: Skipping because of failed dependencies
Notice: /Stage[main]/Xlrelease/Anchor[xlrelease::end]: Dependency Exec[init xl-release] has failures: true
Warning: /Stage[main]/Xlrelease/Anchor[xlrelease::end]: Skipping because of failed dependencies
Notice: Applied catalog in 2.62 seconds
[root@puppetagent1 ~]# 

It will not recover. Maybe the xlrelease_facts.rb can be made more robust.

**Comment by ltutar** [comment]
This is the current file:
[root@puppetagent1 ~]# cat /opt/xl-release/xl-release-server/conf/xl-release-server.conf
admin.password = xebia1
http.port = 5516
jcr.repository.path = repository
ssl = true
http.bind.address = 0.0.0.0
http.context.root = /
importable.packages.path = importablePackages
[root@puppetagent1 ~]#

**Comment by WianVos** [comment]
this issue is dependant on #14
