### ISSUE TITLE
git config item is showing the password in clear text

### ISSUE THREAD

**Issue by ltutar** [xebialabs/puppet-xlrelease#16]
It would be nice not to have the password as clear text with the puppet run.

Notice: /Stage[main]/Xlrelease::Postconfig/Xlrelease_config_item[git]/properties: properties changed '["password", "title", "url", "username"]' to '{"title"=>"git", "url"=>"https://192.168.234.63:8443", "username"=>"admin", "password"=>"admin"}'

**Comment by WianVos** [comment]
It's clear text or noting pall

Sent from my iPhone

On 21 Oct 2015, at 16:42, Levent Tutar <notifications@github.com<mailto:notifications@github.com>> wrote:

It would be nice not to have the password as clear text with the puppet run.

Notice: /Stage[main]/Xlrelease::Postconfig/Xlrelease_config_item[git]/properties: properties changed '["password", "title", "url", "username"]' to '{"title"=>"git", "url"=>"https://192.168.234.63:8443", "username"=>"admin", "password"=>"admin"}'

##

**Comment by ltutar** [comment]
nothing then. we do not want any sensitive information in the puppet logging.

**Comment by WianVos** [comment]
then don't put it in there ..

**Comment by WianVos** [comment]
but you would be adding a manual step to your process

**Comment by ltutar** [comment]
no manual steps
